#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "proxigram"
name = "Proxigram"
description.en = "Privacy focused front-end for Instagram"
description.fr = "Front-end  axé sur la confidentialité pour Instagram"

version = "1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL 3.0"
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://codeberg.org/ThePenguinDev/Proxigram"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://codeberg.org/ThePenguinDev/Proxigram/archive/main.tar.gz"
        sha256 = "6cce1c897ab390b2285933df35ce2e7bbd7ba687fefc44dfdbd85e3f63575a1d"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"

    [resources.ports]

    [resources.apt]
    packages = ""
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
